### PR TITLE
Add SwiftPM support

### PR DESCRIPTION
**Pull request by KleMiX**
Support for Swift Package Manager

### CODE REVIEW

**Comment by EyreFree** [comment]
@KleMiX Thanks for your contribution, 🙏

**Comment by twodayslate** [comment]
I'm getting the following error:
```
https://github.com/EFPrefix/EFColorPicker has no Package.swift manifest for version 5.1.0
```
When adding `https://github.com/EFPrefix/EFColorPicker` via SPM in Xcode 11.3

I think a new release needs to be cut

**Comment by KleMiX** [comment]
> I'm getting the following error:
> 
> ```
> https://github.com/EFPrefix/EFColorPicker has no Package.swift manifest for version 5.1.0
> ```
> 
> When adding `https://github.com/EFPrefix/EFColorPicker` via SPM in Xcode 11.3
> 
> I think a new release needs to be cut

You should specify master branch for now, instead of version. Until new release is available.

**Comment by EyreFree** [comment]
@twodayslate 

Maybe you can try [5.2.0](https://github.com/EFPrefix/EFColorPicker/releases/tag/5.2.0).

**Pull request merged**
